Centos7 docker build file with reprozip
big-data-lab-team/Dockerfiles-HCP-PreFreesurfer pull request #35
Opened 2017-03-17 16:13 UTC by lalet

2017-03-18 01:19 UTC, glatard requested changes

2017-03-18 01:19 UTC, glatard commented on Dockerfile.exec-centos7-reprozip.fslbuild-centos5
> +
Why not start from the existing CentOS7 container (```FROM ...```) and add reprozip to it?

2017-03-18 01:19 UTC, glatard commented on command-line-script.sh
> +ln -s ${EXECUTION_DIR}/${SUBJECT_FOLDER} ${SUBJECT_FOLDER}-${NAME}                       		|| die ${INITDIR} "Cannot link results."
So now this doesn't work in the other containers, right? Maybe you could add a flag to the script so that it works in both cases.

2017-03-21 15:36 UTC, lalet commented on command-line-script.sh
> +ln -s ${EXECUTION_DIR}/${SUBJECT_FOLDER} ${SUBJECT_FOLDER}-${NAME}                       		|| die ${INITDIR} "Cannot link results."
Oh yes. I didn't foresee that.

2017-03-21 18:13 UTC, glatard requested changes

2017-03-21 18:13 UTC, glatard commented on Dockerfile.exec-centos7-reprozip.fslbuild-centos5
> +# numpy - to support FMRIB pipeline execution
why are the package installation lines commented? Just remove them if they aren't used.

2017-03-21 18:13 UTC, glatard commented on Dockerfile.exec-centos7-reprozip.fslbuild-centos5
> +
This Dockerfile still needs to be fixed.

2017-03-21 18:13 UTC, glatard commented on command-line-script.sh
> +  die ${INITDIR} "Needs 2 arguments and an optional flag. Usage: $0 <subject_folder> <name> <True/False>"
This is not the right way to pass a flag. Usage should be `$0 [-r] <subject_folder> <name>` where `-r` is used to activate reprozip.

2017-03-21 18:13 UTC, glatard commented on command-line-script.sh
> +if [${REPROZIP_FLAG}]; then
I think this if statement is always false.

2017-03-21 18:18 UTC, lalet commented on Dockerfile.exec-centos7-reprozip.fslbuild-centos5
> +# numpy - to support FMRIB pipeline execution
These are the short description of libraries used.  These libraries are installed using the yum command after these comments.

2017-03-21 18:20 UTC, lalet commented on command-line-script.sh
> +  die ${INITDIR} "Needs 2 arguments and an optional flag. Usage: $0 <subject_folder> <name> <True/False>"
Okay I will change it

2017-03-22 14:34 UTC, merged